## Linear regression model for student performance prediction

In [51]:
# Importing necessary libraries
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn import metrics

In [12]:
# Read the data
stud_df=pd.read_csv("/content/Student_Performance.csv")

In [13]:
stud_df.keys()

Index(['Hours Studied', 'Previous Scores', 'Extracurricular Activities',
       'Sleep Hours', 'Sample Question Papers Practiced', 'Performance Index'],
      dtype='object')

In [17]:
stud_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     10000 non-null  int64
 1   Previous Scores                   10000 non-null  int64
 2   Extracurricular Activities        10000 non-null  object
 3   Sleep Hours                       10000 non-null  int64
 4   Sample Question Papers Practiced  10000 non-null  int64
 5   Performance Index                 10000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 468.9+ KB

In [21]:
# Defining feature and target labels
X = stud_df[['Hours Studied','Previous Scores','Sleep Hours','Sample Question Papers Practiced']]
y = stud_df['Performance Index']
#printing shapes
print(X.shape, y.shape)

(10000, 4) (10000,)

In [20]:
#creating dataframe from X
df = pd.DataFrame(X, columns=['Hours Studied','Previous Scores','Sleep Hours','Sample Question Papers Practiced','Performance Index'])
df.head()

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,9,1,NaN
1,4,82,4,2,NaN
2,8,51,7,2,NaN
3,5,52,5,2,NaN
4,7,75,8,5,NaN

In [52]:
df.isnull().sum()

Hours Studied                           0
Previous Scores                         0
Sleep Hours                             0
Sample Question Papers Practiced        0
Performance Index                   10000
dtype: int64

In [22]:

# splitting
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=42)
# fitting the model
reg = LinearRegression().fit(X_train, y_train)
# predictions
y_test_pred = reg.predict(X_test)
y_train_pred = reg.predict(X_train)

In [26]:
# Performance metrics
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_test_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_test_pred))
print('R-squared:', metrics.r2_score(y_test, y_test_pred))

Mean Absolute Error: 1.6296726874197016
Mean Squared Error: 4.182254914593815
R-squared: 0.9887144552384186

## New data prediction

In [34]:
stud_df.iloc[0].to_numpy().reshape(1,-1)

array([[np.int64(7), np.int64(99), 'Yes', np.int64(9), np.int64(1),
        np.float64(91.0)]], dtype=object)

In [35]:
stud_pred_df=stud_df.copy()
stud_pred_df = stud_pred_df.drop(columns=['Performance Index'])
stud_pred_df.head(10)

In [44]:
reg.predict(stud_pred_df.iloc[0].to_numpy().reshape(1,-1))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([91.50631428])

In [45]:
# Pickling the file to save the trained model
import pickle
pickle.dump(reg, open('model.pkl', 'wb'))
pickled_model=pickle.load(open('model.pkl', 'rb'))
pickled_model.predict(stud_pred_df.iloc[0].to_numpy().reshape(1,-1))